export const componentCoverage = {
  shell: ["direction", "sidebar", "sonner", "tooltip"],
  dashboard: [
    "alert",
    "avatar",
    "badge",
    "breadcrumb",
    "button",
    "card",
    "chart",
    "dropdown-menu",
    "progress",
    "table",
  ],
  messages: [
    "attachment",
    "bubble",
    "input-group",
    "item",
    "marker",
    "message",
    "message-scroller",
    "scroll-area",
  ],
  settings: [
    "checkbox",
    "field",
    "input",
    "input-otp",
    "label",
    "native-select",
    "radio-group",
    "select",
    "separator",
    "slider",
    "switch",
    "tabs",
    "textarea",
    "toggle",
    "toggle-group",
  ],
  gallery: [
    "accordion",
    "alert-dialog",
    "aspect-ratio",
    "button-group",
    "calendar",
    "carousel",
    "collapsible",
    "combobox",
    "command",
    "context-menu",
    "dialog",
    "drawer",
    "empty",
    "hover-card",
    "kbd",
    "menubar",
    "navigation-menu",
    "pagination",
    "popover",
    "resizable",
    "sheet",
    "skeleton",
    "spinner",
    "toggle-group",
  ],
} as const;

export const coveredComponentNames = [
  ...new Set(Object.values(componentCoverage).flat()),
].toSorted();
